version: "3.4"

services:
  server:
    container_name: authentik
    environment:
      - AUTHENTIK_HOST=${AUTHENTIK_HOST}
      - AUTHENTIK_HOST_BROWSER=${AUTHENTIK_HOST_BROWSER}
      - AUTHENTIK_INSECURE=false
    networks:
      - traefik_proxy
      - default
    labels:
      - traefik.enable=true
      ## HTTP Routers
      - traefik.http.routers.${SERVICE}.entrypoints=https
      - traefik.http.routers.${SERVICE}.rule=Host(`${DOMAIN}`) || HostRegexp(`{subdomain:[a-z0-0]+}.ai.hyeon.pro`) && PathPrefix(`/outpost.goauthentik.io/`)
      - traefik.http.routers.${SERVICE}.tls.certresolver=leresolver
      - traefik.http.services.${SERVICE}.loadbalancer.server.port=9000

########################### NETWORKS
networks:
  traefik_proxy:
    external: true
